import { VStack } from '@chakra-ui/react'
import { type NextPage } from 'next'
import Head from 'next/head'
import { AllCards } from '~/components/CategoryCard/AllCards'
import { Charts } from '~/components/Charts/Charts'
import { Header } from '~/components/Header/Header'
import { Transactions } from '~/components/Transactions/Transactions'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack p={4} spacing={10} align="stretch">
        <Header />
        <AllCards />
        <Charts />
        <Transactions />
      </VStack>
    </>
  )
}

export default Home
